### ISSUE TITLE
Failing Test on Linux/MacOS running Raku 2023-12

### ISSUE THREAD

**Issue by rcmlz** [bduggan/raku-log-async#35]
[Log::Async] # Failed test 'filtered by msg'
[Log::Async] # at t/04-filter.t line 74
[Log::Async] # expected: 'cat alert2'
[Log::Async] #      got: (Any)
[Log::Async] # You failed 1 test of 10

See for details [https://github.com/rcmlz/raku-log-async/actions](https://github.com/rcmlz/raku-log-async/actions)

**Comment by bduggan** [comment]
I've refactored that test to use a simple promise instead of a supply (https://github.com/bduggan/raku-log-async/commit/af14335f45659cc2fef2e7b7111d2e8b574ead8b) ...any luck with the latest master?
