### ISSUE TITLE
ui.select does not provide a way to set the default selection

### ISSUE THREAD

**Issue by Xliff** [bduggan/raku-log-async#37]
It seems no matter what I've been able to try, ui.select does not allow you to set the default selection. I've even tried forcing it in the code  using this:

`$first ?? $p.select-first !! $p.select-visible($p.height.pred);`
 
as opposed to just :

`$p.select-visible($p.height - 1)`

And it still selects the last line (which was set by :cancel)

**Comment by bduggan** [comment]
I guess this is for [Terminal::UI](https://git.sr.ht/~bduggan/raku-terminal-ui) which is on sourcehut...I just went ahead and cloned it onto github for better issue tracking (https://github.com/bduggan/raku-terminal-ui)

**Comment by bduggan** [comment]
But yes, alerts were hard-coded to jump to the last line.  I've just added a "default-row" option to select a given visible line (from 0 to height-1) -- here's the change and an example: https://github.com/bduggan/raku-terminal-ui/commit/1b2155ae4def4101f7a9aecc64dba8eab1782695

**Comment by Xliff** [comment]
Thanks, Brian! Sorry about that misplacement, but I've been working like a
daemon since we've communicated. You solved a bit of a long-time blocker
for a project I've been working on.  I guess I let the coding session go on
a bit longer than it should have and missed the fact that I was on the
wrong service! x_x
